/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author francisco
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Pantalla() {
        initComponents();
        this.setTitle("CODIGO DE RESISTENCIAS");
        int heitgth = 660;
        int width = 500;
        setSize(heitgth, width);
        setLocationRelativeTo(null);
        ajustarimagen();
        
this.getContentPane().setBackground(Color.green);
    }
//AJUSTAR IMAGEN 

    public void ajustarimagen() {
        String rut = "/Principal/resistencia.png";

        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource(rut));
        Image magen = icono.getImage();
        ImageIcon iconoEscalado = new ImageIcon(magen.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_DEFAULT));

        jLabel5.setIcon(iconoEscalado);
//      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        tolerancia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "NEGRO", "MARRON", "ROJO ", "NARANJA", "AMARILLO ", "VERDE", " AZUL", "VIOLETA", "GRIS", "BLANCO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 100, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "NEGRO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "AZUL", "VIOLETA", "GRIS", "BLANCO" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(190, 100, 102, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "NEGRO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "AZUL", "VIOLETA", "GRIS", "BLANCO", "ORO", "PLATA" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(310, 100, 110, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NINGUNO", "ORO", "PLATA", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(420, 100, 110, 30);

        jLabel1.setText("1 banda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(77, 70, 60, 20);

        jLabel2.setText("2 banda");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 70, 70, 20);

        jLabel3.setText("3 banda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 70, 70, 20);

        jLabel4.setText("Tolerancia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 70, 70, 20);

        jLabel5.setBorder(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 170, 270, 120);
        getContentPane().add(resultado);
        resultado.setBounds(40, 360, 100, 28);
        getContentPane().add(tolerancia);
        tolerancia.setBounds(140, 360, 80, 30);

        jLabel7.setText("unidad");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 330, 90, 20);

        jLabel8.setText("Resultado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 320, 100, 30);

        jLabel6.setText("OhmS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 370, 36, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int Banda1() {
        int opcion = jComboBox1.getSelectedIndex();
        switch (opcion) {
            case 0:
                break;
            case 1:
                opcion = 0;
                break;
            case 2:
                opcion = 1;
                break;
            case 3:
                opcion = 2;
                break;
            case 4:
                opcion = 3;
                break;
            case 5:
                opcion = 4;
                break;
            case 6:
                opcion = 5;
                break;
            case 7:
                opcion = 6;
                break;
            case 8:
                opcion = 7;
                break;
            case 9:
                opcion = 8;
                break;
            case 10:
                opcion = 9;
                break;
            default:

                break;
        }
        opcion *= 10;
        return opcion;
    }

    public int Banda2() {

        int opcion2 = jComboBox2.getSelectedIndex();
        switch (opcion2) {

            case 0:

                break;
            case 1:
                opcion2 = 0;
                break;
            case 2:
                opcion2 = 1;
                break;
            case 3:
                opcion2 = 2;
                break;
            case 4:
                opcion2 = 3;
                break;
            case 5:
                opcion2 = 4;
                break;
            case 6:
                opcion2 = 5;
                break;
            case 7:
                opcion2 = 6;
                break;
            case 8:
                opcion2 = 7;
                break;
            case 9:
                opcion2 = 8;
                break;
            case 10:
                opcion2 = 9;
                break;
            default:
                break;
        }

        return opcion2;
    }

    public float Banda3() {

        int seleccion = jComboBox3.getSelectedIndex();
        float opcion3 = 0;
        switch (seleccion) {
            case 0:
    tolerancia.setText("");
                break;
            case 1:
                opcion3 = 1;//negro
                 tolerancia.setText("");
           
                break;
            case 2:
                opcion3 = 10;//marron
           tolerancia.setText("");
                break;
            case 3:
                opcion3 = 100;//rojo
                   tolerancia.setText("");
             
                break;
            case 4:
                opcion3 = 1000;//naranja
           
                    tolerancia.setText("");
                break;
            case 5:
                opcion3 = 10000;//amarillo
               
                   tolerancia.setText("");
                break;
            case 6:
                opcion3 = 100000;//verde
                 tolerancia.setText("");
              
                break;
            case 7:
                opcion3 = 1000000;//azul
        
                    tolerancia.setText("");
                break;
            case 8:
                opcion3 = 10000000; //violeta
                   tolerancia.setText("");
                break;
            case 9:
                opcion3 = 0;//gris
                    tolerancia.setText("");
                break;
            case 10:
                opcion3 = 0;//blanco
                tolerancia.setText("");
          
                break;
            case 11:
                opcion3 = (float) 0.1;//oro
                tolerancia.setText("");
                break;
            case 12:
                opcion3 = (float) 0.01;//plata
                tolerancia.setText("");
                break;
            default:
                break;

        }

        return opcion3;
    }

    public void tolerancia() {
        int seleccion = jComboBox4.getSelectedIndex();

        switch (seleccion) {
            case 0:
                 tolerancia.setText("");
                break;
            case 1:
 tolerancia.setText("+/- 5%");
                break;
            case 2:
tolerancia.setText("+/- 10%");
                break;
        }
    }

    public String Calcular() {
        float resul;
        resul = (Banda1() + Banda2()) * Banda3();
        DecimalFormat d = new DecimalFormat("0.00");
        d.format(resul);
        return d.format(resul);

    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        // TODO add your handling code here:
        resultado.setText("" + Calcular());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        resultado.setText(Calcular());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        resultado.setText(Calcular());
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
tolerancia();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField resultado;
    private javax.swing.JLabel tolerancia;
    // End of variables declaration//GEN-END:variables
}
